### ISSUE TITLE
errors with daily update script

### ISSUE THREAD

**Issue by ahmedmohiduet** [altova/SECDB#10]
So now I'm getting this error with my daily update script:
RaptorXMLXBRL.exe script scripts\daily_update.py --db=db\edgar.db3 --retries=10 --log=logs\daily_update_id{instance-id()}.log 
usage: daily_update.py [-h] [--db DSN] [--db-driver {sqlite,odbc}]
                       [--create-tables] [--log LOGFILE]
                       [--threads MAXTHREADS] [--cik CIK] [--recompute]
                       [--store-fact-mappings]
                       [RSS [RSS ...]]
daily_update.py: error: unrecognized arguments: --retries=10

If I ommit retries argument. it days "maxretries argument missing".

Thanks in Advance.

**Comment by afalk42** [comment]
As per our previous response on issue #8 the --retries option had been added to the download_filings.py script. We have now also added this to the daily_update.py script.

But please do realize that this is open-source. You are free to modify these scripts as you see fit to solve your particular challenge. You cannot expect us to solve every little problem for you...
