### ISSUE TITLE
Mappings

### ISSUE THREAD

**Issue by auenbauer** [altova/SECDB#11]
I have shortly looked at the BS, IS and CF mapping files and wanted to find out if I understand them correctly. 

There is a total 12.318 "concepts" (names like "DebtCurrent") and somewhat fewer distinct concepts because a concept can belong to one, two or three statement types (BS, IS and/or CF). 

To me it looks like that in 1.360 cases you have more "levels" for mapping the names: 

 "DebtCurrent": {
        "add-to": [
            "shortTermDebt",
            "shortTermDebt",
            "currentLiabilitiesOther",
            "accountsPayable",
            "longTermDebt",
            "nonCurrentLiabilitiesOther"
        ]

Does that mean that you try to map "DebtCurrent" to "shortTermDebt" (level 1) first and if it fails you go down one level or is there something different going on?  Does it mean something special when a term like  "shortTermDebt" is mentioned twice?

Thank you for your great contribution on this.

Best regards, 

GLeitold, Graz, Austria

**Comment by auenbauer** [comment]
I have looked at the 4 "names/concepts" with the highest number of "levels" (7) but I am unable to understand how the mapping is done because the accounting concepts seem relatively unrelated to me:


![image](https://user-images.githubusercontent.com/14974013/29135904-eb849314-7d3b-11e7-84f4-229a847f95c1.png)

**Comment by afalk42** [comment]
The mappings were generated by an internal classifier application that attempts to match the reported XBRL SEC filings with the high-level BS/IS/CF values on the various public platforms for financial reports, e.g. Yahoo/Google/Fidelity/etc. finance pages.
In our experience, some of these XBRL filings use almost arbitrary concepts everywhere, and only the labels made them appear to look correct in the SEC's interactive data viewer. This situation has gotten better in recent years, with the work of the DQC (data quality committee) at xbrl.us (see [https://xbrl.us/data-quality/committee/](https://xbrl.us/data-quality/committee/)), which Altova is a member of, but for processing the older filings we still need to keep this heuristic mapping.
As a result of this process, the mappings will look strange for a human being, although they do indeed contain only concept names that were actually used in XBRL SEC filings.

To answer your specific questions:

> Does that mean that you try to map "DebtCurrent" to "shortTermDebt" (level 1) first and if it fails you go down one level or is there something different going on? Does it mean something special when a term like "shortTermDebt" is mentioned twice?

The "add-to" array in the mappings do not stand for different levels, these are just concept names that we use for computation of the BS/IS/CF line-items. The entries should have been made unique, the duplicates (like “shortTermDebt”) have no meaning (currently duplicate entries are skipped during computation).

> I have looked at the 4 "names/concepts" with the highest number of "levels" (7) but I am unable to understand how the mapping is done because the accounting concepts seem relatively unrelated to me.

The concepts are sometimes really completely unrelated, but they were actually used in real world XBRL filings with the SEC.

Hope this helps und mit freundlichen Grüßen in meine alte Heimat,
A.Falk

**Comment by auenbauer** [comment]
Many thanks for your thorough explanation.  

This is an interesting field and I am curious to find out which machine learning algorithms (and/or combinations thereof) would be best able to come up with an optimized classifier that can be applied on a "firm-by-firm" and "report-by-report" basis to get to better quality normalized statements (historically and going forward).  My assumption is that based on how easy it is to derive the reports/data that a classifier could be trained (almost) in real-time. 

My understanding is that companies like Bloomberg are still doing a lot of manual work to normalize the data (which also leads to inconsistencies and mistakes). 

Probably an analyst/investment manager would want to fully understand the mapping (classifier) and then add some adjustments to the numbers based on his thinking & investment strategy.

Liebe Grüße

gl
