### ISSUE TITLE
10-Q, 10-K do not work for 2019 (perhaps more)

### ISSUE THREAD

**Issue by deios0** [altova/SECDB#12]
There is a new format (iXBRL) for sec filings from 2019. Before, there were files like bac-20180930.xml (https://www.sec.gov/Archives/edgar/data/70858/000007085818000042/0000070858-18-000042-index.htm), but at the moment there are new names for XML files: bac-331201910xq_htm.xml (https://www.sec.gov/Archives/edgar/data/70858/000007085819000026/0000070858-19-000026-index.htm).

As a result, Raptor does not download filings and we get an error in the database:
FatalError: I/O operation on file 'file:///path_to_file/raptor_xml/' failed.
Details: System Error 21: Is a directory

Thanks

**Comment by xmldev** [comment]
Dear deios0,
thank you for your interest! We are very aware of this issue in the published code. The original intention was that this "_... project will **demonstrate** how to write Python scripts using RaptorXML's XBRL engine..._".  Please note that RaptorXML+XBRL naturally processes inlineXBRL instances but we'll archive this repository without further code updates.
