### ISSUE TITLE
Unable to pull filings for local rss feeds after 11-2019

### ISSUE THREAD

**Issue by gjb117** [altova/SECDB#14]
I'm currently using the trial license for RaptorXML+XBRL Server on MacOS (I've enjoyed it very much so far and considering whether to purchase the paid sub). I was able to download successfully the rss feeds between 2016-now executing `download_feeds.py` (2016 was just an arbitrary date I picked for testing purposes). Moving on to the xbrl filing downloads, I was successfull with executing `download_filings.py` on feeds from 2016 to 10/2019, after which point I began encountering the following errors:

`RuntimeError: Failed loading RSS feed file:///Users/greg/SECDB/feeds/xbrlrss-2020-02.xml: Error: file:///Users/greg/SECDB/feeds/xbrlrss-2020-02.xml:6: Element <atom:link> is not allowed under element <channel>.
  Reason: The following elements are expected at this location
    'atom:link'
  Hint: Element <atom:link> is in namespace 'https://www.w3.org/2005/Atom', but a correspondent element from namespace 'http://www.w3.org/2005/Atom' would be permitted.
  Details:
    cvc-complex-type.1.4: Element <atom:link> unexpected by type '{anonymous}' of element <channel>.
    cvc-type.3.2: Element <channel> is not valid with respect to type definition '{anonymous}'.
    cvc-elt.5.2.1: The element <channel> is not valid with respect to the actual type definition '{anonymous}'.
Error: file:///Users/greg/SECDB/feeds/xbrlrss-2020-02.xml:18: Element <edgar:xbrlFiling> is not allowed under element <item>.
  Reason: The following elements are expected at this location
    'edgar:xbrlFiling'
  Hint: Element <edgar:xbrlFiling> is in namespace 'https://www.sec.gov/Archives/edgar', but a correspondent element from namespace 'http://www.sec.gov/Archives/edgar' would be permitted.
  Details:
    cvc-complex-type.1.4: Element <edgar:xbrlFiling> unexpected by type '{anonymous}' of element <item>.
    cvc-type.3.2: Element <item> is not valid with respect to type definition '{anonymous}'. ... Info: Processing was aborted after reporting 100 error(s). Please increase the error limit to report additional errors.`

Any guidance or explanation regarding the error and the best way to resolve would be greatly appreciated. 

**Update:** Have included the full, relevant portion of the errors, truncated for brevity (as its just the same error at different lines). It seemed I was able to resolve the first namespace issue with `atom` by simply changing the ns attribute for `xmlns:atom` to use `http:`. Unclear if this is an appropriate fix given the remaining context to address above, and whether there will be undesired side effects.

**Comment by gjb117** [comment]
I should also note that I experienced a similar error but with the ‘atom’ namespace. I suppose I was able to resolve by modifying the ns to http: ... in the rss xml (although not sure what side effects that will have). Perhaps that’s the solution to error above, but any initial clarification would be great...thank you

**Comment by xmldev** [comment]
fixed! thanks for reporting :)
