### ISSUE TITLE
Giving 'The product has no license assigned on the server.' still after setting up evaluation license

### ISSUE THREAD

**Issue by ahmedmohiduet** [altova/SECDB#2]
I have setup and uploaded 30 days trail license file into local license server.
But it is still giving following error:

C:\Program Files\Altova\RaptorXMLXBRLServer2016\bin>RaptorXMLXBRL.exe script scripts\build_secdb.py --db=d
\edgar.db3 --log=logs\log_create.txt --create-tables
Error: Cannot load license from LicenseServer ('["localhost"]').
  There were no available licenses for this product
    The product has no license assigned on the server.
    There was a problem communicating with the LicenseServer at the address '["localhost"]'

Am I missing something?

**Comment by afalk42** [comment]
It sounds like either the license is not assigned to the server software yet, or the license server isn't running. Please feel free to contact our free technical support via this Support form for all RaptorXML server installation and license server related questions: http://www.altova.com/support_supportform.asp
Also, the detailed steps for installation can be found int he online help here: http://manual.altova.com/RaptorXML/raptorxmlxbrlserver/index.html?srvstpwin_installation.htm
