### ISSUE TITLE
Store into postgresql

### ISSUE THREAD

**Issue by ahmedmohiduet** [altova/SECDB#4]
Hello,

Can you guide us through storing crawl data into postgresql rather than sqlite. I am looking for something like:
RaptorXMLXBRL.exe script scripts\build_secdb.py feeds\xbrlrss-2010-*.xml --db=SOME_HOST:5432/DATABASE_NAME --log=logs\log_2010.txt

I am not sure where I can get started for this
- Mohiuddin

**Comment by afalk42** [comment]
We have already added preliminary support for ODBC during the development of the scripts. At the time of development we have tested it a few times with a local MS SQL Server DB, but ODBC support is not as well tested, as sqllite support. Still, it should be sufficient to get you started with connecting to postgresql or any other DB.
In the [build_secdb.py](https://github.com/altova/SECDB/blob/master/scripts/build_secdb.py) script there is already a --db-driver option that accepts the values ‘sqlite’ (default) and ‘odbc’. When using --db-driver=odbc, the --db option is used to specify the ODBC connection string. Please also note that [the 3rd party library pyodbc needs to be installed](http://manual.altova.com/RaptorXML/pyapiv2/html/intro.html#extending-the-custom-raptorxml-python-interpreter-with-pip).
Hopefully this will be sufficient to get you started...
In case you want to implement native postgresql support (e.g. py-postgresql), the relevant functions that require modifications are setup_db_connect() and maybe create_db_tables(), so you could create a fork of this project and do it there...
