### ISSUE TITLE
Corrpted/Incomplete zip files

### ISSUE THREAD

**Issue by ahmedmohiduet** [altova/SECDB#5]
So I have downloaded & parsed 2 years of filings. My script:

RaptorXMLXBRL.exe script scripts\download_filings.py feeds\xbrlrss-2015-12.xml
ping 127.0.0.1 -n 6 > nul
RaptorXMLXBRL.exe script scripts\build_secdb.py feeds\xbrlrss-2015-12.xml --db=db\edgar.db3 --log=logs\log_2015-12.txt
rm -rf filings\2015-12
................................................
......................................
RaptorXMLXBRL.exe script scripts\download_filings.py feeds\xbrlrss-2015-12.xml
ping 127.0.0.1 -n 6 > nul
RaptorXMLXBRL.exe script scripts\build_secdb.py feeds\xbrlrss-2014-01.xml --db=db\edgar.db3 --log=logs\log_2014-01.txt
rm -rf filings\2014-01

 Found about 52k filings in DB. But among 7k filings I found in the DB 'errors' field in filings table  NOT NULL saying "IO operation failed on zip files. Is it may be a cause because the site is blocking crawler after certain amount of requests and unblocking again after some time.

Am I missing something here!

**Comment by afalk42** [comment]
The download_filings.py script accepts also a --log option which should track any HTTP exceptions/errors.
In case of errors, please rerun the download_filings.py script after fixing any possible network connectivity problems.
The script will only try to re-downloaded any missing or corrupted files (by comparing file sizes from the RSS feed).
