### ISSUE TITLE
Regarding daily updates

### ISSUE THREAD

**Issue by ahmedmohiduet** [altova/SECDB#6]
Can you briefly describe of what this daily_update.py script do when I do?

RaptorXMLXBRL.exe script scripts\daily_update.py --db=db\edgar.db3 --log=logs\daily_update_id{instance-id()}.log

Does it automatically remove downloaded new+old filings and then deletes them after inserting interested data into DB?
Do we have to delete downloaded filings manually?

Thanks in Advance.

**Comment by afalk42** [comment]
The daily_update.py script performs the following tasks:

1)  Download latest EDGAR RSS feeds
2)  Download any new/missing filings (as zip archives) from the SEC
3)  Process the new filings and add new records to the DB

The script does not delete the downloaded zip archives, this needs to be done manually.
