### ISSUE TITLE
Refresh/Reload a single filing data in DB

### ISSUE THREAD

**Issue by ahmedmohiduet** [altova/SECDB#7]
How can I refresh a single filing data as in DB in 'filings' table 'errors' field shows I/O error with certain XXXXXXX-XX-XXXXXXXX.zip file.
So how can I redownload the one single filing and refresh the filing data in DB?

**Comment by afalk42** [comment]
Recomputing selective filings and updating the DB can be accomplished by specifying the --recompute and --cik options with the build_secdb.py script.

First, please update build_secdb.py from the Altova github repository (as we have found a bug during testing)! Then, the database can be updated for a given company with the following steps:
1.  Delete the zip archive from the filings/20YY-MM/ sub-directory
2.  Re-download it with raptorxmlxbrl script scripts/download_filings.py feeds/xbrlrss-20YY-MM.xml
3.  Update the database with raptorxmlxbrl scripts/build_secdb.py --recompute --cik=123456 --db=... --log=... feeds/xbrlrss-20YY-MM.xml
